name: Go linter check

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "backend/**"

jobs:
  linters:
    name: Go linter check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
      
      - name: Download go dependencies
        run: |
          cd go
          go mod download

      - name: Add Go bin to PATH
        run: |
          echo "${{ runner.tool_cache }}/go/$(go version | awk '{ print $3 }')/*/bin" >> $GITHUB_PATH

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: "v1.60"
          working-directory: "go"